# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Alex Pacheco
tagline:          
description:      
url:              https://www.alexpacheco.net
baseurl:          /

author:
  name:           'Alex Pacheco'
  url:            https://www.alexpacheco.net

#paginate:         

# Custom vars
version:          

github:
  repo:           https://github.com/alexpacheco
